kind: pipeline
name: test
steps:
- name: echo only
  image: golang
  when:
    event:
    - pull_request
    action:
    - opened
  commands:
  - echo "this only triggers on open"
- name: all pr events
  image: golang
  when:
    event:
    - pull_request
  commands:
  - echo "this only triggers on open"
